services:
  econemon_bootsy_database:
    class: Econemon\Bootsy\DatabaseBundle\Service\DatabaseService
    calls:
      - [ setDbConnection, ["@database_connection"]]
      - [ setKernel, ["@kernel"]]

  econemon_bootsy_database_frontend:
    class: Econemon\Bootsy\DatabaseBundle\Controller\DbAdminController
    parent: econemon_bootsy_base_controller
    calls:
      - [ setFormFactory, ["@form.factory"]]
