db_versions:
  path: /versions
  defaults: { _controller: econemon_bootsy_database_frontend:versionsAction }

db_run_updates:
  path: /versions/run
  defaults: { _controller: econemon_bootsy_database_frontend:runUpdatesAction }

db_status:
  path: /status
  defaults: { _controller: econemon_bootsy_database_frontend:statusAction }

db_configure:
  path: /configure
  defaults: { _controller: econemon_bootsy_database_frontend:configureAction }