imports:
    - { resource: config.yml }
    - { resource: "@EconemonBootsyApplicationBundle/Resources/config/config_dev.yml" }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
