imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

services:
  error_service:
    class: Hfietz\ErrorBundle\Service\ErrorService
    arguments: ['@kernel']
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  db_service:
    class: Hfietz\DatabaseBundle\Service\DatabaseService
    calls:
      - [ setDbConnection, ["@database_connection"]]
      - [ setKernel, ["@kernel"]]

  db_admin_frontend:
    class: Hfietz\DatabaseBundle\Controller\DbAdminController
    calls:
      - [ setTemplateEngine, ["@templating"]]
      - [ setRouter, ["@router"]]
      - [ setFormFactory, ["@form.factory"]]

doctrine:
  dbal:
    driver: '%database_driver%'
    host: '%database_host%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'