login:
  path: /login
  defaults: { _controller: HfietzAccessBundle:Session:login }

db_admin:
  resource: "@HfietzDatabaseBundle/Resources/config/routing.yml"
  prefix: /admin/db

errors:
  resource: "@HfietzErrorBundle/Resources/config/routing.yml"
  prefix: /admin/errors
