user:
  resource: "@EconemonBootsyUserBundle/Resources/config/routing.yml"

app:
  resource: "@EconemonBootsyApplicationBundle/Resources/config/routing.yml"

db_admin:
  resource: "@EconemonBootsyDatabaseBundle/Resources/config/routing.yml"
  prefix: /admin/db

errors:
  resource: "@EconemonBootsyErrorBundle/Resources/config/routing.yml"
  prefix: /admin/errors
