services:
  econemon_bootsy_base:
    abstract: true
    arguments: ['@kernel']

  econemon_bootsy_base_controller:
    abstract: true
    calls:
      - [ setRouter, ["@router"]]
      - [ setTemplateEngine, ["@templating"]]

  econemon_bootsy_menu:
    class: Econemon\Bootsy\ApplicationBundle\Service\MenuManager

  econemon_bootsy_main:
    class: Econemon\Bootsy\ApplicationBundle\Controller\MainController
    calls:
      - [ setTemplateEngine, ["@templating"]]

  econemon_bootsy_menu_controller:
    class: Econemon\Bootsy\ApplicationBundle\Controller\MenuController
    parent: econemon_bootsy_base_controller
    calls:
      - [ setSecurityContext, [ '@security.context' ] ]
      - [ setAccessMap, [ '@security.access_map' ]]
      - [ setAccessDecisionManager, [ '@security.access.decision_manager' ]]

  econemon_bootsy_config:
    class: Econemon\Bootsy\ApplicationBundle\Service\ConfigManager
    parent: econemon_bootsy_base

  econemon_bootsy_registry:
    class: Econemon\Bootsy\ApplicationBundle\Service\RegistryService
    arguments: ['@kernel']
