services:
  econemon_bootsy_base:
    abstract: true
    arguments: ['@kernel']

  econemon_bootsy_base_controller:
    abstract: true
    calls:
      - [ setRouter, ["@router"]]
      - [ setTemplateEngine, ["@templating"]]
      - [ setSession, ["@session"]]
      - [ setTranslator, ["@translator"]]
      - [ setValidator, [ "@validator" ] ]

  econemon_bootsy_base_form:
    abstract: true
    calls:
      - [ setTranslator, ["@translator"]]

  econemon_boosty_form_type_fieldset:
    class: Econemon\Bootsy\ApplicationBundle\Form\FieldsetType
    tags:
      - { name: form.type, alias: fieldset }

  econemon_bootsy_menu:
    class: Econemon\Bootsy\ApplicationBundle\Service\MenuManager

  econemon_bootsy_mailer:
    class: Econemon\Bootsy\ApplicationBundle\Service\TemplateMailer
    calls:
      - [ setSwift, [ "@mailer" ] ]
      - [ setTwig, [ "@twig" ] ]

  econemon_bootsy_menu_controller:
    class: Econemon\Bootsy\ApplicationBundle\Controller\MenuController
    parent: econemon_bootsy_base_controller
    calls:
      - [ setAccessMap, [ '@security.access_map' ]]
      - [ setAccessDecisionManager, [ '@security.access.decision_manager' ]]

  econemon_bootsy_config:
    class: Econemon\Bootsy\ApplicationBundle\Service\ConfigManager
    parent: econemon_bootsy_base

  econemon_bootsy_registry:
    class: Econemon\Bootsy\ApplicationBundle\Service\RegistryService
    arguments: ['@kernel']
