services:
  econemon_bootsy_base:
    abstract: true
    arguments: ['@kernel']

  econemon_bootsy_menu:
    class: Econemon\Bootsy\ApplicationBundle\Service\MenuManager

  econemon_bootsy_menu_controller:
    class: Econemon\Bootsy\ApplicationBundle\Controller\MenuController
    calls:
      - [ setTemplateEngine, ["@templating"]]
      - [ setSecurityContext, [ '@security.context' ] ]

  econemon_bootsy_config:
    class: Econemon\Bootsy\ApplicationBundle\Service\ConfigManager
    parent: econemon_bootsy_base

  econemon_bootsy_registry:
    class: Econemon\Bootsy\ApplicationBundle\Service\RegistryService
    arguments: ['@kernel']
