services:
  econemon_bootsy_user:
    class: Econemon\Bootsy\UserBundle\Service\UserService
    parent: econemon_bootsy_base
  econemon_bootsy_user_profile_form:
    class: Econemon\Bootsy\UserBundle\Form\ProfileFormType
    arguments: [ '%fos_user.model.user.class%' ]
    tags:
      - { name: form.type, alias: econemon_bootsy_user_profile }

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Econemon\Bootsy\UserBundle\Entity\User
  from_email:
    address: "%system_email_address%"
    sender_name: "%system_email_sender%"
  service:
    mailer: fos_user.mailer.twig_swift
  registration:
    confirmation:
      enabled: true
  profile:
    form:
      type: econemon_bootsy_user_profile
