econemon_bootsy_user_profile_edit:
  path: /profile/edit
  defaults: { _controller: econemon_bootsy_user_controller:editProfileAction }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

# override the bundle's route with our own, redirecting to what is an admin page in our application
fos_user_registration_register:
  path: /register/
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: econemon_bootsy_user_new
    permanent: true

# override the bundle's route to point to the same page as a password reset (because the way we set this up it works the same)
fos_user_registration_confirm:
  path: /register/confirm/{token}
  defaults:
    _controller: FOSUserBundle:Resetting:reset
    methods: [ GET, POST ]

econemon_bootsy_user_new:
  path: /admin/user/new
  defaults: { _controller: econemon_bootsy_user_controller:newUserAction }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile