services:
  econemon_bootsy_user:
    class: Econemon\Bootsy\UserBundle\Service\UserService
    parent: econemon_bootsy_base
  econemon_bootsy_user_profile_form:
    class: Econemon\Bootsy\UserBundle\Form\ProfileFormType
    arguments: [ '%fos_user.model.user.class%' ]
    tags:
      - { name: form.type, alias: econemon_bootsy_user_profile }
  econemon_bootsy_user_fos_user_event_listener:
    class: Econemon\Bootsy\UserBundle\Event\FOSUserEventListener
    calls:
      - [ 'setRouter', ['@router'] ]
    tags:
      - { name: kernel.event_subscriber }
  econemon_bootsy_user_controller:
    class: Econemon\Bootsy\UserBundle\Controller\UserController
    parent: econemon_bootsy_base_controller
    calls:
      - [ 'setUserManager', [ '@fos_user.user_manager' ] ]
      - [ 'setProfileFormFactory', [ '@fos_user.profile.form.factory' ] ]
      - [ 'setPasswordFormFactory', [ '@fos_user.change_password.form.factory' ] ]