Econemon\Bootsy\UserBundle\Entity\User:
    type:  entity
    table: app_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      name:
        type: string
        length: 255
      phone:
        type: string
        length: 255
